#!/usr/bin/env bash
set -euo pipefail

DEFAULT_REPO_URL="https://github.com/ChenMiaoi/kernlab.git"
DEFAULT_SUPPORT_SUBMODULES="busybox qemu"
GENERATED_MARKER="# Generated by kernlab scripts/bootstrap.sh."

usage() {
    cat <<EOF
Usage: bootstrap.sh

Create a Linux-first QEMU workspace. Intended for:
  curl -fsSL https://raw.githubusercontent.com/ChenMiaoi/kernlab/main/scripts/bootstrap.sh | bash

Default workspace layout in the current directory:
  linux/                 Linux source tree users edit
  .kernlab/              cloned template, QEMU, BusyBox, and scripts
  qemu-linux.mk          workspace-local build/runtime config
  Makefile               wrapper; run 'make run' from the workspace root

Default behavior:
  - Clone the template over HTTPS from ${DEFAULT_REPO_URL}
  - Install into ${PWD} unless INSTALL_DIR is set
  - Initialize support submodules inside .kernlab: ${DEFAULT_SUPPORT_SUBMODULES}
  - Clone Linux to \${INSTALL_DIR}/linux unless LINUX_DIR points at an existing tree
  - Refuse to overwrite unrelated directories or changed generated workspace files

Environment variables:
  REPO_URL             Template Git repository URL (default: ${DEFAULT_REPO_URL})
  BRANCH               Optional template branch, tag, or commit-ish for git clone --branch
  INSTALL_DIR          Workspace directory (default: ${PWD})
  SUPPORT_SUBMODULES   Space-separated template support submodules (default: ${DEFAULT_SUPPORT_SUBMODULES})
                       SUBMODULES is accepted as a compatibility alias.
  SUBMODULE_DEPTH      Support/Linux clone depth; set to 0 or empty for full history (default: 1)
  ENSURE_BUILD_DEPS    Set to 1 to let init-template.sh prepare build dependencies (default: 0)
  PYTHON_BIN           Python interpreter for dependency preparation (default: python3)
  LINUX_DIR            Existing Linux source tree to use; bootstrap will not modify it
  WORKSPACE_LINUX_DIR  Workspace path to clone Linux into (default: \${INSTALL_DIR}/linux)
  LINUX_URL            Linux Git repository URL (default: template linux submodule URL)
  LINUX_BRANCH         Optional Linux branch, tag, or commit-ish for git clone --branch

Examples:
  curl -fsSL https://raw.githubusercontent.com/ChenMiaoi/kernlab/main/scripts/bootstrap.sh | bash
  INSTALL_DIR=~/src/my-kernel curl -fsSL https://raw.githubusercontent.com/ChenMiaoi/kernlab/main/scripts/bootstrap.sh | bash
  LINUX_DIR=/home/me/src/linux curl -fsSL https://raw.githubusercontent.com/ChenMiaoi/kernlab/main/scripts/bootstrap.sh | bash
  LINUX_URL=https://github.com/me/linux.git LINUX_BRANCH=my-topic curl -fsSL https://raw.githubusercontent.com/ChenMiaoi/kernlab/main/scripts/bootstrap.sh | bash
  REPO_URL=https://github.com/me/kernlab.git BRANCH=main INSTALL_DIR=~/src/my-kernel curl -fsSL https://raw.githubusercontent.com/ChenMiaoi/kernlab/main/scripts/bootstrap.sh | bash
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Missing required command: $1" >&2
        exit 1
    fi
}

is_empty_dir() {
    local dir="$1"
    [[ -d "${dir}" ]] || return 1
    ( shopt -s nullglob dotglob; entries=("${dir}"/*); ((${#entries[@]} == 0)) )
}

abs_path() {
    local path="$1"
    if [[ "${path}" == /* ]]; then
        printf '%s\n' "${path}"
    else
        printf '%s\n' "${PWD}/${path}"
    fi
}

repo_slug() {
    local url="$1"
    url="${url%.git}"
    url="${url#git@github.com:}"
    url="${url#https://github.com/}"
    url="${url#http://github.com/}"
    printf '%s\n' "${url}"
}

is_template_repo() {
    local dir="$1"
    local expected_slug actual_url actual_slug

    [[ -d "${dir}/.git" || -f "${dir}/.git" ]] || return 1
    [[ -f "${dir}/qemu-linux.mk" && -x "${dir}/scripts/init-template.sh" ]] || return 1

    expected_slug="$(repo_slug "${REPO_URL}")"
    actual_url="$(git -C "${dir}" remote get-url origin 2>/dev/null || true)"
    actual_slug="$(repo_slug "${actual_url}")"

    [[ "${actual_slug}" == "${expected_slug}" || "${actual_slug}" == "ChenMiaoi/kernlab" ]]
}

run_template_init() {
    local template_dir="$1"
    echo "Initializing template support submodules at ${template_dir}"
    REPO_DIR="${template_dir}" \
    SUBMODULE_DEPTH="${SUBMODULE_DEPTH}" \
    SUBMODULES="${SUPPORT_SUBMODULES}" \
    ENSURE_BUILD_DEPS="${ENSURE_BUILD_DEPS}" \
    PYTHON_BIN="${PYTHON_BIN}" \
        "${template_dir}/scripts/init-template.sh"
}

fail_existing_path() {
    echo "$1" >&2
    echo "Choose another INSTALL_DIR/LINUX_DIR, or move the existing path yourself before retrying." >&2
    exit 1
}

linux_dir_is_explicit() {
    [[ "${LINUX_DIR_EXPLICIT}" == "1" && "$(abs_path "${LINUX_DIR}")" == "${WORKSPACE_LINUX_DIR_ABS}" ]]
}

validate_workspace_entry() {
    local entry="$1"
    local base="${entry##*/}"

    case "${base}" in
        .kernlab)
            if [[ ! -d "${entry}" ]] || ! is_template_repo "${entry}"; then
                fail_existing_path "Existing .kernlab is not this template repository: ${entry}"
            fi
            ;;
        linux)
            if [[ "$(abs_path "${entry}")" == "${WORKSPACE_LINUX_DIR_ABS}" ]]; then
                if is_empty_dir "${entry}" || linux_dir_is_explicit; then
                    return 0
                fi
                fail_existing_path "Existing workspace linux/ is non-empty. Set LINUX_DIR=${entry} to use it explicitly."
            fi
            fail_existing_path "Unexpected existing linux directory: ${entry}"
            ;;
        Makefile|qemu-linux.mk|out)
            ;;
        *)
            fail_existing_path "INSTALL_DIR contains an unrelated existing path: ${entry}"
            ;;
    esac
}

validate_workspace() {
    local entry

    if [[ -e "${INSTALL_DIR}" && ! -d "${INSTALL_DIR}" ]]; then
        fail_existing_path "INSTALL_DIR exists and is not a directory: ${INSTALL_DIR}"
    fi

    if [[ ! -e "${INSTALL_DIR}" ]]; then
        mkdir -p "${INSTALL_DIR}"
        return 0
    fi

    if is_empty_dir "${INSTALL_DIR}"; then
        return 0
    fi

    shopt -s nullglob dotglob
    for entry in "${INSTALL_DIR}"/*; do
        validate_workspace_entry "${entry}"
    done
    shopt -u nullglob dotglob
}

clone_repo() {
    local url="$1"
    local dest="$2"
    local branch="$3"
    local -a clone_args=(clone)

    if [[ -n "${SUBMODULE_DEPTH}" && "${SUBMODULE_DEPTH}" != "0" ]]; then
        clone_args+=(--depth "${SUBMODULE_DEPTH}")
    fi
    if [[ -n "${branch}" ]]; then
        clone_args+=(--branch "${branch}")
    fi
    clone_args+=("${url}" "${dest}")
    git "${clone_args[@]}"
}

clone_linux_at_commit() {
    local url="$1"
    local dest="$2"
    local commit="$3"
    local parent="${dest%/*}"
    local -a fetch_args=(fetch)

    [[ "${parent}" == "${dest}" ]] && parent="."
    mkdir -p "${parent}"
    git init "${dest}"
    git -C "${dest}" remote add origin "${url}"
    if [[ -n "${SUBMODULE_DEPTH}" && "${SUBMODULE_DEPTH}" != "0" ]]; then
        fetch_args+=(--depth "${SUBMODULE_DEPTH}")
    fi
    fetch_args+=(origin "${commit}")
    git -C "${dest}" "${fetch_args[@]}"
    git -C "${dest}" checkout --detach FETCH_HEAD
}

clone_linux() {
    local template_dir="$1"
    local linux_url linux_commit

    if [[ "${LINUX_DIR_EXPLICIT}" == "1" ]]; then
        if [[ ! -d "${LINUX_DIR}" ]]; then
            fail_existing_path "LINUX_DIR does not exist or is not a directory: ${LINUX_DIR}"
        fi
        echo "Using existing Linux source tree: ${LINUX_DIR}"
        return 0
    fi

    if [[ -e "${WORKSPACE_LINUX_DIR_ABS}" && ! -d "${WORKSPACE_LINUX_DIR_ABS}" ]]; then
        fail_existing_path "Linux destination exists and is not a directory: ${WORKSPACE_LINUX_DIR_ABS}"
    fi
    if [[ -d "${WORKSPACE_LINUX_DIR_ABS}" ]] && ! is_empty_dir "${WORKSPACE_LINUX_DIR_ABS}"; then
        fail_existing_path "Linux destination is non-empty. Set LINUX_DIR=${WORKSPACE_LINUX_DIR_ABS} to use it explicitly."
    fi

    linux_url="${LINUX_URL:-$(git -C "${template_dir}" config --file .gitmodules --get submodule.linux.url)}"
    linux_commit="$(git -C "${template_dir}" rev-parse HEAD:linux 2>/dev/null || true)"

    echo "Cloning Linux source into ${WORKSPACE_LINUX_DIR_ABS}"
    if [[ -n "${LINUX_BRANCH:-}" ]]; then
        clone_repo "${linux_url}" "${WORKSPACE_LINUX_DIR_ABS}" "${LINUX_BRANCH}"
    elif [[ -n "${linux_commit}" ]]; then
        clone_linux_at_commit "${linux_url}" "${WORKSPACE_LINUX_DIR_ABS}" "${linux_commit}"
    else
        clone_repo "${linux_url}" "${WORKSPACE_LINUX_DIR_ABS}" ""
    fi
}

generated_config_content() {
    cat <<EOF
${GENERATED_MARKER}
# Workspace-local config. Edit values here; do not edit .kernlab for kernel experiments.

TEMPLATE_DIR := \$(CURDIR)/.kernlab
LINUX_DIR ?= ${CONFIG_LINUX_DIR}
BUSYBOX_DIR ?= \$(TEMPLATE_DIR)/busybox
QEMU_DIR ?= \$(TEMPLATE_DIR)/qemu
OUT_DIR ?= \$(CURDIR)/out/\$(ARCH)
INITRAMFS_DIR ?= \$(CURDIR)/out/initramfs/\$(ARCH_CANON)
BUSYBOX_OUT_DIR ?= \$(CURDIR)/out/busybox/\$(ARCH_CANON)
QEMU_BUILD_DIR ?= \$(CURDIR)/out/qemu/\$(ARCH_CANON)
EOF
}

generated_makefile_content() {
    cat <<'EOF'
# Generated by kernlab scripts/bootstrap.sh.
# Workspace wrapper; template implementation lives under .kernlab.

SHELL := /usr/bin/env bash
TEMPLATE_DIR := $(CURDIR)/.kernlab
CONFIG_FILE := $(CURDIR)/qemu-linux.mk
SUPPORT_SUBMODULES ?= busybox qemu
INIT_SUBMODULES := $(if $(filter undefined,$(origin SUBMODULES)),$(SUPPORT_SUBMODULES),$(SUBMODULES))
.DEFAULT_GOAL := x86

.PHONY: init %
init:
	@$(MAKE) -f "$(TEMPLATE_DIR)/Makefile" REPO_DIR="$(TEMPLATE_DIR)" CONFIG_FILE="$(CONFIG_FILE)" SUBMODULES="$(INIT_SUBMODULES)" init

%:
	@$(MAKE) -f "$(TEMPLATE_DIR)/Makefile" REPO_DIR="$(TEMPLATE_DIR)" CONFIG_FILE="$(CONFIG_FILE)" "$@"
EOF
}

write_generated_file() {
    local path="$1"
    local content="$2"
    local comparable="${content%$'\n'}"

    if [[ -e "${path}" ]]; then
        if [[ -f "${path}" && "$(<"${path}")" == "${comparable}" ]]; then
            return 0
        fi
        fail_existing_path "Refusing to overwrite changed or unrelated generated file: ${path}"
    fi

    printf '%s' "${content}" >"${path}"
}

generate_workspace_files() {
    local config_content makefile_content
    config_content="$(generated_config_content)"
    config_content+=$'\n'
    makefile_content="$(generated_makefile_content)"
    makefile_content+=$'\n'

    write_generated_file "${INSTALL_DIR}/qemu-linux.mk" "${config_content}"
    write_generated_file "${INSTALL_DIR}/Makefile" "${makefile_content}"
}

REPO_URL="${REPO_URL:-${DEFAULT_REPO_URL}}"
INSTALL_DIR="$(abs_path "${INSTALL_DIR:-${PWD}}")"
TEMPLATE_DIR="${INSTALL_DIR}/.kernlab"
SUBMODULE_DEPTH="${SUBMODULE_DEPTH-1}"
SUPPORT_SUBMODULES="${SUPPORT_SUBMODULES-${SUBMODULES-${DEFAULT_SUPPORT_SUBMODULES}}}"
ENSURE_BUILD_DEPS="${ENSURE_BUILD_DEPS:-0}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

if [[ -n "${LINUX_DIR+x}" ]]; then
    LINUX_DIR_EXPLICIT=1
    LINUX_DIR="$(abs_path "${LINUX_DIR}")"
    WORKSPACE_LINUX_DIR_ABS="${LINUX_DIR}"
    CONFIG_LINUX_DIR="${LINUX_DIR}"
elif [[ -n "${WORKSPACE_LINUX_DIR+x}" ]]; then
    LINUX_DIR_EXPLICIT=0
    WORKSPACE_LINUX_DIR_ABS="$(abs_path "${WORKSPACE_LINUX_DIR}")"
    CONFIG_LINUX_DIR="${WORKSPACE_LINUX_DIR_ABS}"
else
    LINUX_DIR_EXPLICIT=0
    WORKSPACE_LINUX_DIR_ABS="${INSTALL_DIR}/linux"
    CONFIG_LINUX_DIR="\$(CURDIR)/linux"
fi

require_cmd git

validate_workspace

if [[ -e "${TEMPLATE_DIR}" ]]; then
    if ! is_template_repo "${TEMPLATE_DIR}"; then
        fail_existing_path "Existing .kernlab is not this template repository: ${TEMPLATE_DIR}"
    fi
else
    echo "Cloning template ${REPO_URL} into ${TEMPLATE_DIR}"
    clone_repo "${REPO_URL}" "${TEMPLATE_DIR}" "${BRANCH:-}"
fi

run_template_init "${TEMPLATE_DIR}"
clone_linux "${TEMPLATE_DIR}"
generate_workspace_files

editor_cmd="${EDITOR:-editor}"

cat <<EOF

Workspace initialized: ${INSTALL_DIR}
Next steps:
EOF
if [[ "${INSTALL_DIR}" != "$(abs_path "${PWD}")" ]]; then
    printf '  cd %q\n' "${INSTALL_DIR}"
fi
cat <<EOF
  ${editor_cmd} linux/          # edit kernel source
  ${editor_cmd} qemu-linux.mk   # optional build/runtime config
  make run
EOF
